insert into dbo.Productos ([PRO_Nombre],[PRO_Valor],[PRO_Cantidad],[PRO_FechaCreacion])
values ('Bateria AA',20000,200,GETDATE())
insert into dbo.Productos ([PRO_Nombre],[PRO_Valor],[PRO_Cantidad],[PRO_FechaCreacion])
values ('Cargador',20000,200,GETDATE())
insert into dbo.Productos ([PRO_Nombre],[PRO_Valor],[PRO_Cantidad],[PRO_FechaCreacion])
values ('Audifonos',20000,200,GETDATE())
insert into dbo.Productos ([PRO_Nombre],[PRO_Valor],[PRO_Cantidad],[PRO_FechaCreacion])
values ('Cables de Carga',20000,200,GETDATE())
insert into dbo.Productos ([PRO_Nombre],[PRO_Valor],[PRO_Cantidad],[PRO_FechaCreacion])
values ('Alcohol',20000,200,GETDATE())
insert into dbo.Productos ([PRO_Nombre],[PRO_Valor],[PRO_Cantidad],[PRO_FechaCreacion])
values ('Cable USB',20000,200,GETDATE())
insert into dbo.Productos ([PRO_Nombre],[PRO_Valor],[PRO_Cantidad],[PRO_FechaCreacion])
values ('Bateria 9V',20000,200,GETDATE())
insert into dbo.Productos ([PRO_Nombre],[PRO_Valor],[PRO_Cantidad],[PRO_FechaCreacion])
values ('Bateria AAA',20000,200,GETDATE())
insert into dbo.Productos ([PRO_Nombre],[PRO_Valor],[PRO_Cantidad],[PRO_FechaCreacion])
values ('Interruptor',20000,200,GETDATE())
insert into dbo.Productos ([PRO_Nombre],[PRO_Valor],[PRO_Cantidad],[PRO_FechaCreacion])
values ('Luz LED',20000,200,GETDATE())
insert into dbo.Productos ([PRO_Nombre],[PRO_Valor],[PRO_Cantidad],[PRO_FechaCreacion])
values ('Switch',20000,200,GETDATE())
insert into dbo.Productos ([PRO_Nombre],[PRO_Valor],[PRO_Cantidad],[PRO_FechaCreacion])
values ('TomaCorriente',20000,200,GETDATE())
