insert into Facturacion ([FAC_IdProducto],[FAC_IdCliente],[FAC_FechaVenta])
values (1,1,'2000-05-02')
insert into Facturacion ([FAC_IdProducto],[FAC_IdCliente],[FAC_FechaVenta])
values (1,1,'2000-01-02')
insert into Facturacion ([FAC_IdProducto],[FAC_IdCliente],[FAC_FechaVenta])
values (2,2,'2000-02-02')
insert into Facturacion ([FAC_IdProducto],[FAC_IdCliente],[FAC_FechaVenta])
values (3,2,'2000-03-02')
insert into Facturacion ([FAC_IdProducto],[FAC_IdCliente],[FAC_FechaVenta])
values (4,3,'2000-04-02')
insert into Facturacion ([FAC_IdProducto],[FAC_IdCliente],[FAC_FechaVenta])
values (1,3,'2000-03-02')
insert into Facturacion ([FAC_IdProducto],[FAC_IdCliente],[FAC_FechaVenta])
values (1,4,'2000-04-02')
insert into Facturacion ([FAC_IdProducto],[FAC_IdCliente],[FAC_FechaVenta])
values (1,5,'2000-05-02')
insert into Facturacion ([FAC_IdProducto],[FAC_IdCliente],[FAC_FechaVenta])
values (6,8,'2000-06-02')
insert into Facturacion ([FAC_IdProducto],[FAC_IdCliente],[FAC_FechaVenta])
values (1,7,'2000-06-02')
insert into Facturacion ([FAC_IdProducto],[FAC_IdCliente],[FAC_FechaVenta])
values (7,11,'2000-06-02')
insert into Facturacion ([FAC_IdProducto],[FAC_IdCliente],[FAC_FechaVenta])
values (1,11,'2000-08-02')