insert into dbo.Productos ([PRO_Nombre],[PRO_Valor],[PRO_Cantidad],[PRO_FechaCreacion])
values ('Bateria AA',2000,4,GETDATE())
insert into dbo.Productos ([PRO_Nombre],[PRO_Valor],[PRO_Cantidad],[PRO_FechaCreacion])
values ('Cargador',20000,20,GETDATE())
insert into dbo.Productos ([PRO_Nombre],[PRO_Valor],[PRO_Cantidad],[PRO_FechaCreacion])
values ('Audifonos',15000,20,GETDATE())
insert into dbo.Productos ([PRO_Nombre],[PRO_Valor],[PRO_Cantidad],[PRO_FechaCreacion])
values ('Cables de Carga',17000,2,GETDATE())
insert into dbo.Productos ([PRO_Nombre],[PRO_Valor],[PRO_Cantidad],[PRO_FechaCreacion])
values ('Alcohol',20000,20,GETDATE())
insert into dbo.Productos ([PRO_Nombre],[PRO_Valor],[PRO_Cantidad],[PRO_FechaCreacion])
values ('Cable USB',4000,3,GETDATE())
insert into dbo.Productos ([PRO_Nombre],[PRO_Valor],[PRO_Cantidad],[PRO_FechaCreacion])
values ('Bateria 9V',10000,20,GETDATE())
insert into dbo.Productos ([PRO_Nombre],[PRO_Valor],[PRO_Cantidad],[PRO_FechaCreacion])
values ('Bateria AAA',1500,10,GETDATE())
insert into dbo.Productos ([PRO_Nombre],[PRO_Valor],[PRO_Cantidad],[PRO_FechaCreacion])
values ('Interruptor',20000,4,GETDATE())
insert into dbo.Productos ([PRO_Nombre],[PRO_Valor],[PRO_Cantidad],[PRO_FechaCreacion])
values ('Luz LED',10000,5,GETDATE())
insert into dbo.Productos ([PRO_Nombre],[PRO_Valor],[PRO_Cantidad],[PRO_FechaCreacion])
values ('Switch',5000,30,GETDATE())
insert into dbo.Productos ([PRO_Nombre],[PRO_Valor],[PRO_Cantidad],[PRO_FechaCreacion])
values ('TomaCorriente',20000,5,GETDATE())
